import {
  WiDaySunny,
  WiNightFog,
  WiNightClear,
  WiDayFog,
  WiDaySunnyOvercast,
  WiNightAltPartlyCloudy,
  WiNightPartlyCloudy,
  WiCloudy,
  WiNightCloudyHigh,
  WiRain,
  WiRainWind,
  WiNightRainWind,
  WiShowers,
  WiFog,
  WiRaindrops,
  WiRainMix,
  WiSleet,
  WiSnow,
  WiSnowWind,
  WiDayThunderstorm,
  WiNightAltThunderstorm,
  WiDaySnowThunderstorm,
} from "weather-icons-react";

const image = (Component, size) => <Component size={size} />;

export const getIcon = (weatherCode, size, isDay) => {
  return {
    0: image(isDay ? WiDaySunny : WiNightClear, size),
    1: image(isDay ? WiDaySunnyOvercast : WiNightPartlyCloudy, size),
    2: image(isDay ? WiDaySunnyOvercast : WiNightAltPartlyCloudy, size),
    3: image(isDay ? WiCloudy : WiNightCloudyHigh, size),
    45: image(isDay ? WiDayFog : WiNightFog, size),
    48: image(isDay ? WiFog : WiFog, size),
    51: image(isDay ? WiRaindrops : WiRaindrops, size),
    53: image(isDay ? WiRaindrops : WiRaindrops, size),
    55: image(isDay ? WiRain : WiRain, size),
    56: image(isDay ? WiRainMix : WiRainMix, size),
    57: image(isDay ? WiRainMix : WiRainMix, size),
    61: image(isDay ? WiShowers : WiShowers, size),
    63: image(isDay ? WiRain : WiRain, size),
    65: image(isDay ? WiRainWind : WiNightRainWind, size),
    66: image(isDay ? WiSleet : WiSleet, size),
    67: image(isDay ? WiSleet : WiSleet, size),
    71: image(isDay ? WiSnow : WiSnow, size),
    73: image(isDay ? WiSnow : WiSnow, size),
    75: image(isDay ? WiSnow : WiSnow, size),
    77: image(isDay ? WiSnow : WiSnow, size),
    80: image(isDay ? WiShowers : WiShowers, size),
    81: image(isDay ? WiShowers : WiShowers, size),
    82: image(isDay ? WiShowers : WiShowers, size),
    85: image(isDay ? WiSnowWind : WiSnowWind, size),
    86: image(isDay ? WiSnowWind : WiSnowWind, size),
    95: image(isDay ? WiDayThunderstorm : WiNightAltThunderstorm, size),
    96: image(isDay ? WiDaySnowThunderstorm : WiDaySnowThunderstorm, size),
    99: image(isDay ? WiDaySnowThunderstorm : WiDaySnowThunderstorm, size),
  }[weatherCode];
};
